### ISSUE TITLE
Load Case Issue

### ISSUE THREAD

**Issue by Marco-Pellegrino** [diego-apellaniz/KarambaPack#1]
Hi Diego,
I do really like your approach in generating the load case.
I am noticing some weird behavior of the tool when I try to create some load case.
The displacements don't match with mine approach.

Would you mind to have a look?

https://drive.google.com/file/d/1N4GFlsx_eNPF6Iqeo8lRq90Qg-pMbTl_/view?usp=sharing

![image](https://user-images.githubusercontent.com/53620289/117655766-694c9b80-b18f-11eb-84e3-438cf1fc66c8.png)

**Comment by diego-apellaniz** [comment]
Hello Marco,

thanks for your comment and for letting me know about this issue. I think I have fixed it now:
https://github.com/diego-apellaniz/KarambaPack/releases/tag/v1.0.1

there was a bug which caused sometimes a mismatch in the cross sections of the output model.

**Comment by Marco-Pellegrino** [comment]
Perfect!
The tool seems to work as expected now :)
