### ISSUE TITLE
Duplicating lines 

### ISSUE THREAD

**Issue by RyoOm** [diego-apellaniz/KarambaPack#2]
Hi, I use your component. It’s very good to analysis natural period considering additional loads.

I have a trouble when I use the Mass Source Component. Outmodel has twice as many elements as Inmodel. I think two elements are overlapping. I hope you check this behavior and update this program. 

I use Karamba3D 2.0.0_210623_WIP.

Thank you.

**Comment by RyoOm** [comment]
Hi, I use your component. It’s very good to analysis natural period considering additional load. Thank you.
I have a trouble that when I use

**Comment by diego-apellaniz** [comment]
Hello,
thanks for letting me know. I have created a new release v1.0.2 in which this issue should be solved.

**Comment by RyoOm** [comment]
Hi, thank you for your fixing code. I tried ver. 1.0.2, but I wonder the duplication problem seems to be remained.
I tried this component on  Karamba 2.0.0 in both Rhino6 and Rhino7.

Would you mind if I ask you to check your code again? or let me know if you have no problem in your circumstances. 
Thank you.

**Comment by diego-apellaniz** [comment]
Hello, that's extrange. Anyway I have added a new release v1.0.3 with a minor improvement. Could you download this new version and let me know if the error persists?

![image](https://user-images.githubusercontent.com/48953695/126767651-6a865f09-e47f-4db5-ba1d-2b519f14371c.png)

**Comment by RyoOm** [comment]
Hi, I tried v1.0.3. The duplication problem has been solved in my environment.
Thank you very much!

![image](https://user-images.githubusercontent.com/78643821/126782875-1920d91e-f567-418f-8d65-7c0a104b4ea6.png)
