### ISSUE TITLE
Karamba Pack for Karamba 2.0.2

### ISSUE THREAD

**Issue by Marco-Pellegrino** [diego-apellaniz/KarambaPack#3]
Hi Diego,
is there any plan to update your tool to follow the update from Karamba3d?
Do you suggest me to downgrade to version 2.0.0 in order to use your tool?

Best,
Marco

**Comment by diego-apellaniz** [comment]
Hello Marco,
I've just tested the plugin with the Karamba version "2.2.0.1-beta_210709 for RHINO 7" from July 9 and the plugin is still working. Did you experience any problem?
Best,
Diego

**Comment by Marco-Pellegrino** [comment]
Hi Diego,
I'll try to downgrade my Karamba version.
It could be that I have installed Karamba with the new package manager.
I'll keep you posted :)

**Comment by Marco-Pellegrino** [comment]
@diego-apellaniz 
All good :)
It would be great to make the tool working with the latest release as well.
I know that there is a new load type and it was giving issue with the component.
Thanks for the work. It is really helpful and I have pushed my company to change the way we were doing load combination :)

**Comment by diego-apellaniz** [comment]
Hello @Marco-Pellegrino ,
I'm glad that you're using it! I've just updated it (see releases). If something doesn't work just let me know please!
BR Diego
