### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Marco-Pellegrino** [diego-apellaniz/KarambaPack#4]
Hi @diego-apellaniz 
A little request/question for you.

Are you going to update your nice tool to work with of of the latest version of Karamba3d?
Probably, the latest that it seems to work is 2.0.0 210212

We do love to use your tool but there has been some changes in KarambaLoad type and your tool stop to work.
It would be amazing if you can fix it

**Comment by diego-apellaniz** [comment]
Hi @Marco-Pellegrino ,
I've just updated the plugin to the newest Karamba version. You can find the files under Releases.
Sorry for the delay...
BR Diego
