### ISSUE TITLE
1. Solution exception: Non-constant, distributed moment load with Y- and Z-components encountered.

### ISSUE THREAD

**Issue by Marco-Pellegrino** [diego-apellaniz/KarambaPack#5]
Hi @diego-apellaniz 
I have found this issue.
Karamba doesn't raise any error and he is able to run the analyses.
Any thought?

You can download the file in here for testing :)
https://drive.google.com/file/d/16oYTe69_TrzE1uysoGv6nthgJd3yw-F9/view?usp=sharing

![image](https://user-images.githubusercontent.com/53620289/141455799-e4af5f9b-7968-4c82-a67f-aca1dd375154.png)

**Comment by diego-apellaniz** [comment]
Hello Marco,
I’m really sorry, but I‘ve decided not to go on with the development of this project. Karamba will implement Load Combinations very soon and the new Karamba Component “Model Query” already replaces my component for LCA.
I hope it doesn’t cause too much trouble to your workflows. I just can’t find time to update the plugin after each Karamba release. I didn’t plan for that…
Thank you very much for your support all this time.
Best regards,
Diego
