### ISSUE TITLE
Beam View / Shell view "% of range" based on different envelope values creating weird display plot. 

### ISSUE THREAD

**Issue by CamilleChev** [diego-apellaniz/KarambaPack#6]
This is not something new and I'm sure others would have asked this already. When it comes to looking at displacements of a combined beam and shell model, the render setting based on "% of range" is then producing 2 different ranges one for beam elements and one for the shell elements. To get a nice display plot we need to look at "absolute value" and manually type the maximum value for each load cases. 
If this is possible It would be great if the "% of range" was based on [the smallest value of both ranges , biggest value of both range] instead. 
Thank you for your work.

**Comment by diego-apellaniz** [comment]
Hello Camille, can't it be that your beams and shells are not really attached to each other? Anyway if this is a general question to Karamba and not to my extension components you should submit it here I think:
https://discourse.mcneel.com/c/grasshopper/karamba3d/91
Best regards,
Diego
